# Generated by Django 5.2.5 on 2025-11-02 08:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icon', models.CharField(default='fas fa-folder', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cookies/')),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('strawberry', 'Strawberry'), ('oatmeal', 'Oatmeal'), ('peanut_butter', 'Peanut Butter'), ('butter', 'Butter'), ('white_chocolate', 'White Chocolate'), ('almond', 'Almond'), ('pistachio', 'Pistachio'), ('caramel', 'Caramel'), ('mint_chocolate', 'Mint Chocolate'), ('cream_cheese', 'Cream Cheese'), ('spice', 'Spice'), ('ube', 'Ube'), ('matcha', 'Matcha'), ('chocolate_hazelnut', 'Chocolate Hazelnut'), ('chocolate_marshmallow', 'Chocolate Marshmallow'), ('almond_oat', 'Almond Oat')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cookies', to='cookie_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hex_id', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('order_type', models.CharField(choices=[('kiosk', 'Kiosk Order'), ('staff', 'Staff Recorded')], default='kiosk', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('gcash', 'GCash'), ('maya', 'Maya'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('completed', 'Completed'), ('voided', 'Voided'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_daily_report', models.BooleanField(default=False)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cookie_app.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_app.cookie')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cookie_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff Member'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('user_registered', 'User Registered'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_completed', 'Order Completed'), ('order_voided', 'Order Voided'), ('cookie_added', 'Cookie Added'), ('cookie_updated', 'Cookie Updated'), ('cookie_deleted', 'Cookie Deleted'), ('inventory_updated', 'Inventory Updated'), ('staff_approved', 'Staff Approved'), ('staff_rejected', 'Staff Rejected'), ('daily_report_submitted', 'Daily Report Submitted')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('affected_model', models.CharField(blank=True, max_length=50, null=True)),
                ('affected_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookie_app.staff')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Administrator')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('staff_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff Member'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('is_active_staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='cookie_app.userprofile'),
        ),
        migrations.CreateModel(
            name='VoidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('void_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_payment_method', models.CharField(max_length=20)),
                ('void_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_voids', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='void_logs', to='cookie_app.order')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_orders', to='cookie_app.staff')),
            ],
            options={
                'ordering': ['-void_date'],
            },
        ),
    ]
