# Generated by Django 5.2.5 on 2025-11-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
