# Generated by Django 5.2.5 on 2025-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0002_rename_phone_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('user_registered', 'User Registered'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_completed', 'Order Completed'), ('order_voided', 'Order Voided'), ('cookie_added', 'Cookie Added'), ('cookie_updated', 'Cookie Updated'), ('cookie_deleted', 'Cookie Deleted'), ('inventory_updated', 'Inventory Updated'), ('staff_approved', 'Staff Approved'), ('staff_rejected', 'Staff Rejected'), ('staff_updated', 'Staff Updated'), ('staff_deactivated', 'Staff Deactivated'), ('staff_activated', 'Staff Activated'), ('staff_deleted', 'Staff Deleted'), ('daily_report_submitted', 'Daily Report Submitted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff Member'), ('pending', 'Pending Approval')], default='pending', max_length=20),
        ),
    ]
