# Generated by Django 5.2.5 on 2025-11-11 06:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0003_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('void_any_order', 'Can void any order'), ('view_all_orders', 'Can view all orders')]},
        ),
        migrations.AddField(
            model_name='order',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of cash received from customer', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Change returned to customer', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
