# Generated by Django 5.2.5 on 2025-11-11 13:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0004_alter_order_options_order_cash_received_order_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('float_type', models.CharField(choices=[('opening', 'Opening Float'), ('additional', 'Additional Change'), ('closing', 'Closing Balance'), ('adjustment', 'Cash Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('adjustment_type', models.CharField(blank=True, choices=[('shortage', 'Shortage'), ('excess', 'Excess'), ('change_add', 'Change Added'), ('change_remove', 'Change Removed')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_floats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('date', 'float_type', 'adjustment_type')},
            },
        ),
    ]
