# Generated by Django 5.2.5 on 2025-11-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0005_cashfloat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashfloat',
            unique_together=set(),
        ),
    ]
