# Generated by Django 5.2.5 on 2025-11-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0006_alter_cashfloat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash')], default='gcash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('voided', 'Voided'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
