# Generated by Django 5.2.5 on 2025-11-15 09:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0008_order_gcash_amount_order_gcash_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Cookie Craze', max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('business_hours', models.CharField(blank=True, help_text='e.g. Mon-Sun, 9:00 AM - 9:00 PM', max_length=200, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate as a percentage (e.g. 12.00 for 12%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gcash_instructions', models.TextField(blank=True, help_text='Instructions shown to customers for GCash payments', null=True)),
                ('gcash_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gcash_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('theme_primary_color', models.CharField(default='#8B4513', max_length=7)),
                ('theme_secondary_color', models.CharField(default='#D2691E', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
