# Generated by Django 5.2.5 on 2025-11-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0010_branch_order_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gcash_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='gcash_receipts/'),
        ),
    ]
