# Generated by Django 5.2.5 on 2025-11-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0011_order_gcash_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_completed_ftue',
            field=models.BooleanField(default=False, help_text='Whether user has completed the First Time User Experience'),
        ),
    ]
