# Generated by Django 5.2.5 on 2025-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0012_userprofile_has_completed_ftue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_completed_ftue',
        ),
        migrations.AddField(
            model_name='customer',
            name='ftue_completed',
            field=models.BooleanField(default=False),
        ),
    ]
