# Generated by Django 5.2.5 on 2025-11-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0013_remove_userprofile_has_completed_ftue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ftue_completed',
        ),
    ]
