# Generated by Django 5.2.5 on 2025-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_app', '0015_customer_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ftue_completed',
            field=models.BooleanField(default=False),
        ),
    ]
